decoration {
    blur {
        enabled = true
        size = 4
        passes = 2
    }
    shadow {
        enabled = true
        range = 15
        color = rgba(0,0,0,0.6)
    }
}

misc {
    vfr = true
}
