# Gaming: disable blur/shadows for max FPS, enable VRR
decoration {
    blur   { enabled = false }
    shadow { enabled = false }
}
misc { vfr = false; no_vd_cursor_hack = true }
general { allow_tearing = true }
