-- wired-dots — Hyprland entry point (Lua port of hyprland.conf)
--
-- NOT WIRED IN YET. This file is a working draft of the .conf -> Lua
-- migration (Hyprland 0.56.2 warns ".conf support will be removed in
-- Hyprland 0.57"). It is not referenced by 06_symlinks.sh or install.sh
-- and does not run today. Two things block flipping the switch:
--
--   1. local-overrides.lua does not exist yet — 02b_user_choices.sh still
--      only generates local-overrides.conf. Needs a matching Lua emitter
--      before this file's dofile() call below does anything useful.
--   2. monitors.lua is user-generated by nwg-displays (excluded from the
--      repo, per README). Whether nwg-displays can even emit Lua monitor
--      blocks is unverified — needs checking before this can replace
--      monitors.conf for real installs.
--
-- Until both are resolved, hyprland.conf (the .conf chain) stays the
-- active entry point. See scripts/06_symlinks.sh.

local HOME = os.getenv("HOME")
local HYPR_DIR = HOME .. "/.config/hypr"

-- local-overrides.lua is generated by the installer (02b_user_choices.sh —
-- NOT YET UPDATED, see note above). Defines BROWSER, FILE_MANAGER globals
-- and the input.kb_layout config. Guarded with pcall — equivalent of the
-- old "hyprlang noerror true" — so a missing file doesn't crash startup.
pcall(dofile, HYPR_DIR .. "/local-overrides.lua")

dofile(HYPR_DIR .. "/keybindings.lua")
dofile(HYPR_DIR .. "/windowrules.lua")

-- monitors.lua is hardware-specific (generated per machine via nwg-displays,
-- see note above), missing on first boot. Guarded the same way.
pcall(dofile, HYPR_DIR .. "/monitors.lua")

dofile(HYPR_DIR .. "/userprefs.lua")

-- Animation profile switch — was $ANIM var + hyprlang dynamic `source =`.
-- Lua gives us a real variable + string concat instead of the old hack.
local ANIM = "smooth"
dofile(HYPR_DIR .. "/animations/" .. ANIM .. ".lua")

-- Workflow (visual/perf profile) switch — same pattern as ANIM above.
-- Unrelated to system power profile (PPD). Cosmetic/GPU only.
local WORKFLOW = "default"
dofile(HYPR_DIR .. "/workflows/" .. WORKFLOW .. ".lua")

-- nvidia.lua is deployed only when GPU=nvidia (installer creates it).
-- Guarded the same way as local-overrides/monitors above.
pcall(dofile, HYPR_DIR .. "/nvidia.lua")
