-- wired-dots — Hyprland entry point (Lua port of hyprland.conf)
--
-- LIVE as of this commit: confirmed on atlas that Hyprland prefers
-- hyprland.lua over hyprland.conf whenever both exist in the same config
-- dir — there is no opt-in step, no flag. The whole hypr/ directory is
-- symlinked as one unit (06_symlinks.sh), so the moment this file exists
-- in the repo it is the active config for every machine that pulls it.
-- (Learned this the hard way: an earlier draft here had an invalid
-- render:explicit_sync key in nvidia.lua, and it surfaced as a real
-- "your config has errors" banner on a live session — see nvidia.lua.)
--
-- IMPORTANT: pcall() around dofile() only catches a MISSING file (dofile
-- throwing "no such file"). It does NOT catch Hyprland rejecting an
-- invalid config key inside a file that DID load — that error reports
-- through Hyprland's own config-error banner regardless of pcall. Every
-- hl.config() key in every file dofile'd from here needs to be verified
-- against the real key list (e.g. `strings /usr/bin/Hyprland | grep -oE
-- '^[a-z_]+:[a-z_]+'`) before it ships, not just wrapped in pcall.
--
-- Known remaining gaps, not yet resolved:
--   1. local-overrides.lua does not exist yet — 02b_user_choices.sh still
--      only generates local-overrides.conf. The dofile() below no-ops
--      until that generator is updated to also emit Lua.
--   2. monitors.lua is user-generated by nwg-displays (excluded from the
--      repo, per README). Whether nwg-displays can even emit Lua monitor
--      blocks is unverified.
--   3. nvidia.lua (like the nvidia.conf it replaced) is committed
--      unconditionally, not actually gated by GPU detection despite its
--      own header claiming otherwise — 04b_gpu_nvidia.sh doesn't touch
--      it. It loads on every machine, Intel included; only mostly-harmless
--      because its remaining keys (cursor:no_hardware_cursors) are
--      genuinely valid everywhere. Real GPU-conditional deployment is a
--      separate, unstarted piece of work.

local HOME = os.getenv("HOME")
local HYPR_DIR = HOME .. "/.config/hypr"

-- local-overrides.lua is generated by the installer (02b_user_choices.sh —
-- NOT YET UPDATED, see note above). Defines BROWSER, FILE_MANAGER globals
-- and the input.kb_layout config. Guarded with pcall — equivalent of the
-- old "hyprlang noerror true" — so a missing file doesn't crash startup.
pcall(dofile, HYPR_DIR .. "/local-overrides.lua")

dofile(HYPR_DIR .. "/keybindings.lua")
dofile(HYPR_DIR .. "/windowrules.lua")

-- monitors.lua is hardware-specific (generated per machine via nwg-displays,
-- see note above), missing on first boot. Guarded the same way.
pcall(dofile, HYPR_DIR .. "/monitors.lua")

dofile(HYPR_DIR .. "/userprefs.lua")

-- Animation profile switch — was $ANIM var + hyprlang dynamic `source =`.
-- Lua gives us a real variable + string concat instead of the old hack.
local ANIM = "smooth"
dofile(HYPR_DIR .. "/animations/" .. ANIM .. ".lua")

-- Workflow (visual/perf profile) switch — same pattern as ANIM above.
-- Unrelated to system power profile (PPD). Cosmetic/GPU only.
local WORKFLOW = "default"
dofile(HYPR_DIR .. "/workflows/" .. WORKFLOW .. ".lua")

-- nvidia.lua is deployed only when GPU=nvidia (installer creates it).
-- Guarded the same way as local-overrides/monitors above.
pcall(dofile, HYPR_DIR .. "/nvidia.lua")
