-- wired-dots — user preferences (Lua port of userprefs.conf)
-- Hardware: keyboard, touchpad, borders, window swallowing
-- Exec-once: all Hyprland user-scope services start here (not systemctl --user)
--
-- kb_layout lives in local-overrides.lua (generated by the installer from
-- --kb-layout / interactive prompt) — NOT yet ported, see hyprland.lua.

hl.config({
    input = {
        touchpad = {
            natural_scroll = true,
            scroll_factor  = 0.15,
        },
    },

    misc = {
        enable_swallow = true,
        swallow_regex  = "(foot|kitty|alacritty|Alacritty|ghostty|Ghostty|org.wezfurlong.wezterm)",
    },

    decoration = {
        rounding = 0,
    },

    general = {
        col = {
            active_border   = { colors = { "rgba(bb9af7ff)", "rgba(50fa7bff)", "rgba(bb9af7ff)" }, angle = 45 },
            inactive_border = { colors = { "rgba(565f89cc)", "rgba(292e42cc)" }, angle = 45 },
        },
    },

    ecosystem = {
        no_update_news = true,
    },
})

-- PATH for ~/.local/bin (wired-dots ships bin/wallpaper, screenshot.sh,
-- cliphist-rofi, power-profile-switch there).
-- SDDM-spawned Hyprland inherits a minimal PATH that excludes ~/.local/bin,
-- so exec-once / binds that call wallpaper or other repo scripts would
-- silently fail without this.
hl.env("PATH", os.getenv("HOME") .. "/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin")

-- Cursor theme env (XWayland apps need these explicitly)
hl.env("XCURSOR_THEME", "phinger-cursors-dark")
hl.env("XCURSOR_SIZE", "24")

-- Session env propagation + user-scope services (exec-once equivalent).
-- Order preserved from userprefs.conf.
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")

    -- Keyring (SSH agent + secret service for Brave, gh-cli, etc.)
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets,pkcs11")

    -- Core Hyprland helpers (need $WAYLAND_DISPLAY — use exec-once, not systemctl)
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprpolkitagent")
    hl.exec_cmd("hyprsunset")

    -- Desktop services
    hl.exec_cmd("swaync")
    hl.exec_cmd("waybar")
    hl.exec_cmd("udiskie --tray")
    hl.exec_cmd("wallpaper set ~/.config/wired-dots/current")

    -- Clipboard (text + image)
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("wl-clip-persist --clipboard regular")
end)

-- Keyboard layout switch: Super + Space
hl.bind(
    "SUPER + SPACE",
    hl.dsp.exec_cmd(
        [[hyprctl switchxkblayout all next && sleep 0.1 && notify-send -t 2000 "Keyboard" "$(hyprctl devices -j | grep -oP '"active_keymap": "\K[^"]+' | head -1)"]]
    ),
    { description = "[Input] cycle keyboard layout" }
)

-- Lid switch: lock + suspend on close
hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("systemctl suspend"), { locked = true })
