animations {
    enabled = true
    bezier = snap, 0.25, 1, 0.5, 1
    animation = windows,     1, 2, snap, slide
    animation = windowsOut,  1, 1, snap, slide
    animation = border,      1, 5, default
    animation = fade,        1, 2, snap
    animation = workspaces,  1, 2, snap, slide
}
