#!/usr/bin/env bash
# wired-dots — phase 02b: persist user choices + generate Hyprland overrides
#
# Reads KB_LAYOUT / WIRED_BROWSER / WIRED_FILE_MANAGER from the environment
# (set by install.sh's parse_flags + interactive_prompts) and produces:
#
#   $HOME/.cache/wired-dots/user-choices.conf   — KEY=VALUE; consumed by
#       03b_core_packages.sh and 03f_aur_packages.sh to inject the chosen
#       browser/fm into the install transaction
#   $REPO_ROOT/hypr/local-overrides.conf        — Hyprland config snippet
#       sourced from hyprland.conf BEFORE userprefs/keybindings; defines
#       $BROWSER, $FILE_MANAGER, and the input { kb_layout = … } block
#
# The Hyprland file lives in the repo dir (because hypr/ is symlinked at
# install time), gitignored. Future PR will move to file-level symlinks
# and put it in $HOME/.config/hypr/ directly.
set -euo pipefail

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPTS_DIR/.." && pwd)"
export REPO_ROOT SCRIPTS_DIR
# shellcheck source=scripts/global_fn.sh
source "$SCRIPTS_DIR/global_fn.sh"

CHOICES_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/wired-dots"
CHOICES_FILE="$CHOICES_DIR/user-choices.conf"
OVERRIDES_FILE="$REPO_ROOT/hypr/local-overrides.conf"

write_choices_file() {
    if [[ "${DRY_RUN:-0}" == "1" ]]; then
        log_info "[dry-run] would write $CHOICES_FILE"
        return 0
    fi
    mkdir -p "$CHOICES_DIR"
    cat >"$CHOICES_FILE" <<EOF
# wired-dots user choices — generated by 02b_user_choices.sh
# Re-run ./install.sh with --kb-layout / --with-browser / --with-file-manager
# to change. Manual edits here are overwritten on each install run.
KB_LAYOUT=${KB_LAYOUT}
BROWSER=${WIRED_BROWSER}
FILE_MANAGER=${WIRED_FILE_MANAGER}
EOF
    log_ok "wrote choices → $CHOICES_FILE"
}

_pkg_to_binary() {
    # Translate the package name a user picks to the actual binary that Hyprland
    # exec'es. Most packages match their binary 1:1; the exceptions live below.
    local pkg="$1"
    case "$pkg" in
        brave-bin)    printf 'brave' ;;
        pcmanfm-gtk3) printf 'pcmanfm' ;;
        *)            printf '%s' "$pkg" ;;
    esac
}

write_hypr_overrides() {
    if [[ "${DRY_RUN:-0}" == "1" ]]; then
        log_info "[dry-run] would write $OVERRIDES_FILE"
        return 0
    fi
    local browser_bin fm_bin
    browser_bin="$(_pkg_to_binary "$WIRED_BROWSER")"
    fm_bin="$(_pkg_to_binary "$WIRED_FILE_MANAGER")"

    cat >"$OVERRIDES_FILE" <<EOF
# wired-dots — generated user overrides
#
# Sourced from hyprland.conf BEFORE userprefs.conf and keybindings.conf so
# the variables resolve at parse time. Regenerated by every install run
# from \$HOME/.cache/wired-dots/user-choices.conf.
#
# DO NOT EDIT — change via ./install.sh --kb-layout=… --with-browser=… etc.

\$BROWSER = ${browser_bin}
\$FILE_MANAGER = ${fm_bin}

input {
    kb_layout = ${KB_LAYOUT}
}
EOF
    log_ok "wrote hypr overrides → $OVERRIDES_FILE"
}

main() {
    log_step "02b" "user choices"
    : "${KB_LAYOUT:?KB_LAYOUT must be set by install.sh main}"
    : "${WIRED_BROWSER:?WIRED_BROWSER must be set by install.sh main}"
    : "${WIRED_FILE_MANAGER:?WIRED_FILE_MANAGER must be set by install.sh main}"

    write_choices_file
    write_hypr_overrides
    log_ok "user choices applied"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then main; fi
